### ISSUE TITLE
Renaming .list

### ISSUE THREAD

**Issue by lachlanjc** [tachyons-css/tachyons-lists#3]
I'm suggesting that we rename `.list`, as its purpose is to make something _not_ look like a list. For example, Basscss [uses `.list-reset`](https://github.com/basscss/basscss/blob/master/modules/typography/index.css#L35-L38) (tbh, I'd be happy to use the same.) Thoughts @mrmrs?

**Comment by abinxzh** [comment]
Suggest a PR for this @lachlanjc. Also, would be useful to rename `.link` to `.link-reset`

**Comment by mrmrs** [comment]
As the author of the code @lachlanjc I'd have to respectfully disagree with your interpretation of the list class and what its purpose is. I would prefer to have not introduce naming colisions with basscss. The basscss class removes padding from the list - this does not affect margin or padding by default, it just removes the list-style-type. As with list, the link class does not reset the link styles. They are styled how I like links to be styled by default - basic functionality with the ability to customize and extend easily.

**Comment by lachlanjc** [comment]
That makes sense @mrmrs. My concern is that one would expect `.list` to make something look like a list (with `list-style-type`), and a different class would make an element look _not_ like a list. It's true, a naming collision isn't good, but maybe there's a way we could rename it that made better sense on both counts?

**Comment by abinxzh** [comment]
@lachlanjc have you proposed this to tachyons-verbose? It might fit better
there (the naming conventions there are more friendly and less designed for
mad vim skills like that of @mrmrs and the main users of this framework).

**Comment by mrmrs** [comment]
The tachyons naming schemes are not designed around vim. Quite the contrary. They are designed around real world user testing of how people adopt and absorb front end code / patterns. Most of these people were not css experts, nor did they use vim.
